# ---------------------------------------------------------------------------
# Public IP auto-detection (only when allowed_cidr is left empty)
# ---------------------------------------------------------------------------
data "http" "myip" {
  count = var.allowed_cidr == "" ? 1 : 0
  url   = "https://checkip.amazonaws.com"
}

locals {
  detected_cidr = var.allowed_cidr != "" ? var.allowed_cidr : "${chomp(data.http.myip[0].response_body)}/32"

  user_data = templatefile("${path.module}/user_data.sh.tftpl", {
    forgevm_version = var.forgevm_version
    xfs_size_gb     = var.forgevm_xfs_size_gb
  })
}

# ---------------------------------------------------------------------------
# Latest Amazon Linux 2023 x86_64 AMI (via the SSM public parameter)
# ---------------------------------------------------------------------------
data "aws_ssm_parameter" "al2023" {
  name = "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
}

# ---------------------------------------------------------------------------
# Networking: use an explicit subnet_id if given, otherwise fall back to the
# account's default VPC (which not every account has).
# ---------------------------------------------------------------------------
data "aws_vpc" "default" {
  count   = var.subnet_id == "" ? 1 : 0
  default = true
}

data "aws_subnets" "default" {
  count = var.subnet_id == "" ? 1 : 0
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default[0].id]
  }
}

data "aws_subnet" "selected" {
  count = var.subnet_id != "" ? 1 : 0
  id    = var.subnet_id
}

locals {
  subnet_id = var.subnet_id != "" ? var.subnet_id : data.aws_subnets.default[0].ids[0]
  vpc_id    = var.subnet_id != "" ? data.aws_subnet.selected[0].vpc_id : data.aws_vpc.default[0].id
}

# ---------------------------------------------------------------------------
# SSH key pair — either generated by Terraform (generate_ssh_key = true) or
# imported from an existing local public key.
# ---------------------------------------------------------------------------
resource "tls_private_key" "this" {
  count     = var.generate_ssh_key ? 1 : 0
  algorithm = "ED25519"
}

resource "local_sensitive_file" "private_key" {
  count           = var.generate_ssh_key ? 1 : 0
  content         = tls_private_key.this[0].private_key_openssh
  filename        = pathexpand(var.generated_key_path)
  file_permission = "0600"
}

locals {
  public_key = var.generate_ssh_key ? tls_private_key.this[0].public_key_openssh : file(pathexpand(var.public_key_path))
}

resource "aws_key_pair" "this" {
  key_name   = var.key_name
  public_key = local.public_key
}

# ---------------------------------------------------------------------------
# Security group: SSH + ForgeVM API, both scoped to allowed_cidr
# ---------------------------------------------------------------------------
resource "aws_security_group" "forgevm" {
  name_prefix = "forgevm-sandbox-"
  description = "ForgeVM sandbox: SSH + ForgeVM API, scoped to a single CIDR"
  vpc_id      = local.vpc_id

  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [local.detected_cidr]
  }

  ingress {
    description = "ForgeVM API"
    from_port   = 7423
    to_port     = 7423
    protocol    = "tcp"
    cidr_blocks = [local.detected_cidr]
  }

  egress {
    description = "All outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "forgevm-sandbox" }

  lifecycle {
    create_before_destroy = true
  }
}

# ---------------------------------------------------------------------------
# EC2 instance
# ---------------------------------------------------------------------------
resource "aws_instance" "forgevm" {
  ami                         = data.aws_ssm_parameter.al2023.value
  instance_type               = var.instance_type
  key_name                    = aws_key_pair.this.key_name
  vpc_security_group_ids      = [aws_security_group.forgevm.id]
  subnet_id                   = local.subnet_id
  associate_public_ip_address = true

  user_data                   = local.user_data
  user_data_replace_on_change = true

  # Native provider path for nested virtualization (recent AWS provider required).
  # When method = "cli", this block is omitted and null_resource.enable_nested_virt
  # enables it after launch instead.
  dynamic "cpu_options" {
    for_each = var.nested_virtualization_method == "provider" ? [1] : []
    content {
      nested_virtualization = "enabled"
    }
  }

  root_block_device {
    volume_type           = "gp3"
    volume_size           = var.root_volume_size
    delete_on_termination = true
    encrypted             = true
  }

  metadata_options {
    http_endpoint = "enabled"
    http_tokens   = "required" # enforce IMDSv2
  }

  tags = { Name = "forgevm-sandbox" }
}

# ---------------------------------------------------------------------------
# Elastic IP (optional). Disabled by default so an idle auto-terminate leaves
# nothing billable behind — the instance's auto-assigned public IP is used
# instead (and is released automatically on terminate). Turn ON if you want a
# stable address across stop/start, e.g. with nested_virtualization_method =
# "cli" (its stop/start would otherwise change the auto-assigned IP).
# ---------------------------------------------------------------------------
resource "aws_eip" "forgevm" {
  count    = var.use_elastic_ip ? 1 : 0
  domain   = "vpc"
  instance = aws_instance.forgevm.id
  tags     = { Name = "forgevm-sandbox" }
}

locals {
  # Address to surface in outputs: the Elastic IP if allocated, otherwise the
  # instance's auto-assigned public IP.
  host_ip = var.use_elastic_ip ? aws_eip.forgevm[0].public_ip : aws_instance.forgevm.public_ip
}

# ---------------------------------------------------------------------------
# CLI fallback: enable nested virtualization on the (stopped) instance, then
# start it again. Only used when nested_virtualization_method = "cli".
# Requires the AWS CLI (>= 2.33.21) on the machine running Terraform.
# ---------------------------------------------------------------------------
resource "null_resource" "enable_nested_virt" {
  count = var.nested_virtualization_method == "cli" ? 1 : 0

  # Ensure the EIP is associated before we stop/start, so the address is stable.
  depends_on = [aws_eip.forgevm]

  triggers = {
    instance_id = aws_instance.forgevm.id
  }

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail
      IID="${aws_instance.forgevm.id}"
      REGION="${var.region}"
      echo "[nested-virt/cli] Stopping $IID ..."
      aws ec2 stop-instances       --region "$REGION" --instance-ids "$IID" >/dev/null
      aws ec2 wait instance-stopped --region "$REGION" --instance-ids "$IID"
      echo "[nested-virt/cli] Enabling nested virtualization ..."
      aws ec2 modify-instance-cpu-options --region "$REGION" \
        --instance-id "$IID" --nested-virtualization enabled >/dev/null
      echo "[nested-virt/cli] Starting $IID ..."
      aws ec2 start-instances       --region "$REGION" --instance-ids "$IID" >/dev/null
      aws ec2 wait instance-running --region "$REGION" --instance-ids "$IID"
      echo "[nested-virt/cli] Done. /dev/kvm will be present after this boot; the forgevm service will pick it up."
    EOT
  }
}

# ---------------------------------------------------------------------------
# Idle cost guard: terminate the instance after sustained low CPU. Terminating
# also deletes the root EBS (delete_on_termination = true), so the bulk of the
# cost stops automatically if the box is left running unused. The built-in EC2
# "terminate" alarm action requires no IAM role.
#
# NOTE: this terminates OUT OF BAND, so Terraform state will then show the
# instance as gone — run `terraform apply` to rebuild, or `terraform destroy`
# to clean up the rest of the stack. CPU is a coarse idle proxy: a sandbox that
# is merely sitting idle also counts as idle.
# ---------------------------------------------------------------------------
resource "aws_cloudwatch_metric_alarm" "idle_terminate" {
  count = var.auto_terminate_idle ? 1 : 0

  alarm_name        = "forgevm-sandbox-idle-terminate"
  alarm_description = "Terminate ForgeVM after ~${var.idle_minutes}m of CPU below ${var.idle_cpu_threshold_percent}%."

  namespace   = "AWS/EC2"
  metric_name = "CPUUtilization"
  statistic   = "Average"
  dimensions  = { InstanceId = aws_instance.forgevm.id }

  comparison_operator = "LessThanThreshold"
  threshold           = var.idle_cpu_threshold_percent
  period              = 300 # 5-minute periods (basic monitoring granularity)
  evaluation_periods  = max(1, ceil(var.idle_minutes / 5))
  treat_missing_data  = "notBreaching" # don't re-fire once the instance is gone

  alarm_actions = ["arn:aws:automate:${var.region}:ec2:terminate"]

  tags = { Name = "forgevm-sandbox" }
}
